![imagen](./img/ejercicios.png)

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [2]:
import numpy as np

In [3]:
my_array = np.arange(10)
filter_odds = np.mod(my_array, 2) > 0
array_1 = np.extract(filter_odds, my_array)
print(array_1[::-1])

[9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [14]:
print(my_array[8:6:-1])
print(my_array[-2:-4:-1])

[8 7]
[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [15]:
print(my_array)
print(my_array[2::-1])

[0 1 2 3 4 5 6 7 8 9]
[2 1 0]


## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [22]:
array_4 = np.arange(1,21).reshape((4,5))
print(array_4)
print("\nInvertir filas y columnas\n", array_4[::-1,::-1])


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

Invertir filas y columnas
 [[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [31]:
print(array_4)
print(f'\nResultado:\n')
# Tomar hasta la fila dos
# Dentro de cada fila tomar las columnas hasta la segunda
print(array_4[:2:, :2:])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

Resultado:

[[1 2]
 [6 7]]


In [38]:

left, right = np.hsplit(array_4, [2])
upper, lower = np.vsplit(left, [2])
print(array_4)
print(f'\nResultado:\n')
print(upper)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

Resultado:

[[1 2]
 [6 7]]


## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [28]:
print(array_4)
print(f'\nResultado:\n')
# Tomar cada fila de dos en dos
# Dentro de cada fila tomar las columnas de dos en dos
print(array_4[::2, ::2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

Resultado:

[[ 1  3  5]
 [11 13 15]]


In [64]:
print(array_4)
upper1, upper2, upper3, upper4 = np.vsplit(array_4, 4)
print(f'\nResultado:\n')
filter_odds = np.mod(upper1, 2) > 0
upper1 = np.extract(filter_odds, upper1)
upper3 = np.extract(filter_odds, upper3)

array_6 = np.vstack([upper1,upper3])
print(array_6)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

Resultado:

[[ 1  3  5]
 [11 13 15]]


## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])


In [36]:
print(array_4)
print(f'\nResultado indicando fila:\n')
print(array_4[:3:, ::-1])
print(f'\nResultado de forma generica:\n')
print(array_4[:-1:, ::-1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

Resultado indicando fila:

[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]]

Resultado de forma generica:

[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]]


In [74]:
print(array_4)
upper1, upper2, upper3, upper4 = np.vsplit(array_4, 4)

print(f'\nResultado:\n')
#print(upper1[:,::-1])
array_7 = np.vstack([upper1[:,::-1],upper2[:,::-1],upper3[:,::-1]])
print(array_7)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

Resultado:

[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]]


## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [40]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])

print(f'\nResultado np.array para crear array de condiciones:\n')
filter_loros = np.array(x == 'Loro')
print(x[filter_loros])

print(f'\nResultado usando condición :\n')
mask_loro = x == 'Loro'
print(x[mask_loro])


Resultado np.array para crear array de condiciones:

['Loro' 'Loro']

Resultado usando condición :

['Loro' 'Loro']


In [42]:
print(f'\nResultado usando np.extract :\n')
print(np.extract(filter_loros, x))




Resultado usando np.extract :

['Loro' 'Loro']


## Ejercicio 9
Crea una secuencia de 20 elementos y transformala en un array compuesto por 2 matrices de 5x2

In [81]:
array_9 = np.arange(20).reshape((2,5,2))
print(array_9)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]


## Ejercicio 10
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])
```

In [82]:
array_4 = np.arange(1,21).reshape((4,5))
print(array_4)
print("\nInvertir filas y columnas\n", array_4[::-1,::-1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

Invertir filas y columnas
 [[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


## Ejercicio 11
Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [43]:
array_11 = np.zeros((10))

print("itemsize: ",array_11.itemsize)
print("total size", array_11.nbytes)
array_11[3] = 1
print(array_11)


itemsize:  8
total size 80
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


## Ejercicio 12
Crea un vector que vaya del 10 al 49

Inviértelo

In [88]:
array_12 = np.arange(10, 50)
print(array_12[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


## Ejericio 13
Encuentra los indices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/)

In [69]:
array_13 = np.array([1,2,0,0,4,0])
array_13 = np.argwhere(array_13 > 0)
print(array_13.tolist())

print(np.array(np.nonzero([1,2,0,0,4,0])))

[[0], [1], [4]]
[[0 1 4]]


## Ejercicio 14
Crea una matriz de numeros aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [47]:
np.random.seed(1234)
array_14 = np.random.randint(1,99, size = (10,10))
print(array_14)
print(f'Min: {np.min(array_14)}')  
print(f'Max: {np.max(array_14)}')

print(f'Min: {np.min(array_14)}')  
print(f'Max: {np.max(array_14)}')

[[48 84 39 54 77 25 16 50 24 27]
 [31 44 31 27 59 93 70 81 74 48]
 [51 77 38 35 39 68 12  1 76 81]
 [ 4  3 20 13 66 76 82 15 72 61]
 [47 29 82 88 14 97 13 70 96 32]
 [90 85 46 17 42 73 57 71 57 87]
 [45 91 84 48 50 19 86 47 38 39]
 [ 8 68  6 48 48 16 35 11 29  5]
 [83 90 56 79 24 51 63 56 85  1]
 [91 34 22 72 69 82 53 65 86 42]]
Min: 1
Max: 97


## Ejercicio 15
Crea un vector aleatorio de tamaño 30 y calcula su media

In [50]:
np.random.seed(1234)
array_15 = np.random.randint(1,100, size = (30))
print(array_15)
print(f'Suma:{np.sum(array_15)}')
print(f'Media:{np.mean(array_15)}')


[48 84 39 54 77 25 16 50 24 27 31 44 31 27 59 93 70 81 74 48 51 77 38 35
 39 68 12  1 76 81]
Suma:1480
Media:49.333333333333336


## Ejercicio 16
Crea un array cuadrado de 2D, con las dimensiones que quiras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [3]:
#Intentar hacerlo con slicing
array_16 = np.zeros((15, 15))
array_16[:1,:] = 1
array_16[-1:,:] = 1
array_16[:,:1] = 1
array_16[:,-1:] = 1
print(array_16)


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [5]:
#Intentar hacerlo con slicing
array_16_2 = np.ones((15, 15))
array_16_2[1:-1,1:-1] = 0
print(array_16_2)


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


## Ejercicio 17
Crea una mtriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [106]:
#Intentar hacerlo con slicing
#Iniciamos todo a 0
array_17 = np.full((8,8), 0)
#Ponemos filas alternas enteras a 1 desde la segunda fila 
array_17[1::2,:] = 1
#Ponemos columnas alternas enteras a 1 desde la segunda columna 
array_17[:,1::2] = 1
# Desde segunda fila, segunda columna asignamos cero de forma alternativa 
array_17[1::2,1::2] = 0
print(array_17)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [6]:
array_17_2 = np.full((8,8), 0)

print("Creamos una matriz de ceros")
print(array_17_2,"\n")
array_17_2[::2,1::2] = 1
#print("Paso uno")
print(array_17_2,"\n")
array_17_2[1::2,::2] = 1
print(array_17_2,"\n")

Creamos una matriz de ceros
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]] 

[[0 1 0 1 0 1 0 1]
 [0 0 0 0 0 0 0 0]
 [0 1 0 1 0 1 0 1]
 [0 0 0 0 0 0 0 0]
 [0 1 0 1 0 1 0 1]
 [0 0 0 0 0 0 0 0]
 [0 1 0 1 0 1 0 1]
 [0 0 0 0 0 0 0 0]] 

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]] 



## Ejercicio 18
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [111]:
azulejo = np.array([[0, 1],
                    [1, 0]])
pared = np.tile(azulejo, (4,4))
pared

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

## Ejercicio 19
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [56]:
np.random.seed(60)
array_19 = np.random.uniform(low=1, high=100, size=(5,5))

media = np.mean(array_19)
desv = np.std(array_19)
print(f'Array:\n{array_19}\nMedia: {media}\nDesviacion: {desv}')

array_19 -= media
array_19 /= desv

print(f'\nArray:\n{array_19}')

Array:
[[30.78645967 19.50763582 32.99508502 66.90920746 57.1301093 ]
 [40.42714193 38.56207664  2.04757205 17.8661945  13.2159437 ]
 [69.54772636 87.5697145  34.40229356 99.25346334 14.02246701]
 [50.53265382 29.37543015 22.83790063 50.70646912 63.97019143]
 [63.93201697  8.96287578 58.56194142 84.07989508 30.00880696]]
Media: 43.48845088802218
Desviacion: 25.613455818105763

Array:
[[-0.49591087 -0.93625847 -0.40968177  0.91439268  0.53259734]
 [-0.11951956 -0.1923354  -1.61793391 -1.00034359 -1.18189859]
 [ 1.01740568  1.72101976 -0.35474156  2.17717644 -1.15041032]
 [ 0.27501962 -0.55100026 -0.80623835  0.28180571  0.79964768]
 [ 0.79815727 -1.34794677  0.5884989   1.58477031 -0.52627197]]


## Ejercicio 20
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya todos los elementos entre el 3 y el 8, por el valor -1
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [62]:
array_20 = np.arange(11)
print(f'1)\n{array_20}')

y = array_20.copy()
y[(y>=3) & (y<=8)] *= -1
print(f'\n2)\n{y}')

1)
[ 0  1  2  3  4  5  6  7  8  9 10]

2)
[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10]


## Ejercicio 21
#### Bonus track. Mini hundir la flota
1. Crea un tablero de 10x10 relleno del carácter espacio ( ).
2. Posiciona un par de barcos en [(0,1), (1,1)] y [(1,3), (1,4), (1,5), (1,6)]. Los barcos serán Os mayúsculas. Como ves, un barco de dos posiciones de eslora y otro de cuatro.
3. Recibe un disparo en uno de los barcos, sustituyendo la O por una X
4. Recibe un disparo en agua, sustituyendo uno de los espacios por un guión: -
5. Ignorando los disparos recibidos, ahora prueba a posicionar otro barco de 4 posiciones dentro del tablero, pero **de manera ALEATORIA.**

**TIP apartado 5**: El barco tendrá una posición inicial aleatoria dentro del tablero, y una orientación también aleatoria (N,S,E,O).

Por ejemplo, si tu posicion inicial fuese (5,0) y la orientación O, no podrias ponerlo porque se sale del tablero. Ahora bien, si fuese orientación este, si podrías, y ocuparía las posiciones [(5,0), (5,1), (5,2), (5,3)]. Por tanto tendrás que iterar con un bucle si es posible encajar el barco en el tablero, y el bucle terminará cuando lo consigas encajar. **Ojo con las posiciones donde ya hay barco!!!**

Usa `import random` para elegir las coordenadas aleatorias.